#/vis/ogl/set/displayListLimit 10000000000
#/vis/viewer/set/viewpointThetaPhi 65 315 deg

#/detector/nonSensitiveMode true
#/detector/trackerMode 111111
#/detector/ecalMode 111
/detector/nonSensitiveMode false
/detector/trackerMode 111111
/detector/ecalMode 111

/run/initialize

/generator particle
/generator/particle/type ~g_Lambda0
/generator/particle/momentum 15 GeV
/generator/particle/eta 0
/generator/particle/sigmaEta 0
/root/setFileName OpenCMSG4_particle.root

/run/beamOn 1
